name: drones-query
namespace: drones
deployment:
  image: "renegmedal/drones-query"
  tag: "v0.0.1"
  replicas: 1
  command: "/root/query"   
  server: nats.nats.svc.cluster.local:4222   

service:
  http_port: 8080
  http_nodePort: 30020
  
  