 

order1:
	curl -XPOST http://localhost:9090/publish -d '{"topic":"ORDER.created","message":"order 1001"}'

order2:
	curl -XPOST http://localhost:9090/publish -d '{"topic":"ORDER.created","message":"order 2001"}'

order3:
	curl -XPOST http://localhost:9090/publish -d '{"topic":"ORDER.update","message":"order 30001"}'	

order4:
	curl -XPOST http://localhost:9090/publish -d '{"topic":"ORDER.update","message":"order 11001"}'		
 