name: website
namespace: website
deployment:
  image: "renegmedal/cinema-nats-website"
  tag: "latest"
  replicas: 1
  command: "/website"
  serveraddr: localhost:8080
  natsaddr: nats.nats.svc.cluster.local:4222
  userstopic: USERS 
  moviestopic: MOVIES 
  showtimestopic: SHOWTIMES 
  bookingstopic: BOOKINGS  

service:
  http_port: 8080
  http_nodePort: 30020
  