{{ if and .Values.nats.externalAccess .Values.nats.advertise }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nats.serviceAccount }}
  # namespace: {{ .Release.Namespace }}
  namespace: {{ .Values.nats.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.nats.serviceAccount }}
  namespace: {{ .Values.nats.namespace }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.nats.serviceAccount }}-binding
  namespace: {{ .Values.nats.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.nats.serviceAccount }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.nats.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{ end }}
