NAME: driver-agent
LAST DEPLOYED: Fri Jul  2 11:59:16 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: driver-agent/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name:  driver-agent  # this will be used by other microservices
  namespace: trans-service
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: driver-agent
  ports:
    - name: http
      port: 8080
      # nodePort: 30020  #http://192.168.49.2:30020/vehicles/City%20Truck

  type: ClusterIP
  #type: NodePort
---
# Source: driver-agent/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-agent
  namespace: trans-service
spec:
  selector:
    matchLabels:
      app: driver-agent
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: driver-agent
    spec:
      containers:
      - name: driver-agent
        image: renegmedal/trans-service-agent:v0.0.1
        command: [
          "/root/driver-agent",
          "-s","nats.nats.svc.cluster.local:4222"]

