NAME: rides-manager
LAST DEPLOYED: Fri Jul  2 12:01:38 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: rides-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name:  rides-manager  # this will be used by other microservices
  namespace: trans-service
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: rides-manager
  ports:
    - name: http
      port: 8080
      # nodePort: 30020  #http://192.168.49.2:30020/vehicles/City%20Truck

  type: ClusterIP
  #type: NodePort
---
# Source: rides-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rides-manager
  namespace: trans-service
spec:
  selector:
    matchLabels:
      app: rides-manager
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: rides-manager
    spec:
      containers:
      - name: rides-manager
        image: renegmedal/trans-service-manager:v0.0.1
        command: [
          "/root/rides-manager",
          "-s","nats.nats.svc.cluster.local:4222"]

