name: ordering-new
namespace: ordering
deployment:
  image: "renegmedal/ordering-new"
  tag: "v0.0.2"
  replicas: 1
  command: "/root/order-new"
  # port: 8080 
  server: nats.nats.svc.cluster.local:4222  
  # durablename: dur-reader 
  # topic: PRODUCT.inserted 

service:
  http_port: 8080
  # http_nodePort: 30020
  
  