name: bookings
namespace: bookings
deployment:
  image: "renegmedal/cinema-nats-bookings"
  tag: "latest"
  replicas: 1
  command: "/bookings"
  serveraddr: localhost:8080
  mongouri: mongodb://bookings-mongodb.bookings.svc.cluster.local:27017 
  enablecredentials: false 
  natsaddr: nats.nats.svc.cluster.local:4222
  topic: BOOKINGS
  queuename: qbookings
  # -serveraddr localhost:4000 -mongouri mongodb://localhost:27017 -enablecredentials=false
service:
  http_port: 8080
  http_nodePort: 30020
  