 
request-suv:
	curl -X POST http://localhost:8282/rides  -d '{"type":"suv", "location": {"lat": 12342243.344, "lng": 345534555.458}}'
 

request-regular:
	curl -X POST http://localhost:8282/rides  -d '{"type":"regular", "location": {"lat": 12342243.344, "lng": 345534555.458}}'
 

request-bus:
	curl -X POST http://localhost:8282/rides  -d '{"type":"bus", "location": {"lat": 12342243.344, "lng": 345534555.458}}'
 