name: users
namespace: users
deployment:
  image: "renegmedal/cinema-nats-users"
  tag: "latest"
  replicas: 1
  command: "/users"
  serveraddr: localhost:8080
  # mongouri: mongodb://users-mongodb:4222 
  mongouri: mongodb://users-mongodb.users.svc.cluster.local:27017 
  enablecredentials: false
  natsaddr: nats.nats.svc.cluster.local:4222
  topic: USERS
  queuename: qusers 

service:
  http_port: 8080
  http_nodePort: 30020
  
  