name: movies
namespace: movies
deployment:
  image: "renegmedal/cinema-nats-movies"
  tag: "latest"
  replicas: 1
  command: "/movies"
  serveraddr: ":8080"
  mongouri: mongodb://movies-mongodb.movies.svc.cluster.local:27017 
  enablecredentials: false 
  natsaddr: nats.nats.svc.cluster.local:4222
  topic: MOVIES
  queuename: qmovies
  
service:
  http_port: 8080
  http_nodePort: 30020
  