name: publisher
deployment:
  image: "renegmedal/js-pattern-publisher"
  tag: "0.1.0"
  replicas: 1
  command: "/publisher"
  port: 8080 
  server: nats.nats.svc.cluster.local:4222  
  streamname: ORDER 
  topic: ORDER.*

  # ./publisher -s nats://localhost:4222 -streamname ORDER -topic ORDER.* -port 9090 

service:
  http_port: 8080
  http_nodePort: 30020
  
  